alias n="neofetch"
alias t="tmux"
alias fish="asciiquarium"
alias wt="wttr Nanchang"
alias on="nvim ~/.config/nvim/lua/core/pack.lua"
alias ra="ranger"
alias cs="cowsay"
alias ll="exa -l --icons"
alias x="startx"
alias c="clear"
alias i3="nvim ~/.config/i3/config"
alias zsh="nvim ~/.zshrc"
alias zim="nvim ~/.zimrc"
alias readme="vim README.md"
alias lg="lazygit"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gd="git diff"
alias proxy-clash="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890"
alias proxy-pigcha="export https_proxy=http://127.0.0.1:15777 http_proxy=http://127.0.0.1:15777"
alias qqconfig="/opt/apps/com.qq.im.deepin/files/run.sh winecfg"
alias wechatconfig="/opt/apps/com.qq.weixin.deepin/files/run.sh winecfg"
